name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          with:
            fetch-depth: 0
      
      - name: setup-go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18
      
      - name: lint
        run: make fmt
      
      - name: build
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
